allowBuilds:
  '@parcel/watcher': true
  '@prisma/client': true
  '@prisma/engines': true
  argon2: true
  esbuild: true
  msw: true
  prisma: true
minimumReleaseAgeExclude:
  - h3@2.0.1
  - h3@2.0.1-rc.15
  - h3@2.0.1-rc.18
  - fast-uri@3.1.1
  - fast-uri@3.1.2
  - qs@6.15.2
  - hono@4.12.21
  - brace-expansion@5.0.6
  - esbuild@0.28.1
  - tar@7.5.16
  - vite@7.3.5
  - js-yaml@4.1.2
  - '@babel/core@7.29.1'
  - hono@4.12.25
overrides:
  '@hono/node-server@<1.19.13': '>=1.19.13'
  h3@>=2.0.0 <=2.0.1-rc.14: '>=2.0.1-rc.15'
  h3@>=2.0.0-0 <2.0.1-rc.15: '>=2.0.1-rc.15'
  h3@>=2.0.0-beta.0 <=2.0.1-rc.16: '>=2.0.1-rc.17'
  h3@>=2.0.0-beta.4 <2.0.1-rc.18: '>=2.0.1-rc.18'
  h3@>=2.0.1-alpha.0 <=2.0.1-rc.16: '>=2.0.1-rc.17'
  hono@<4.12.16: '>=4.12.16'
  ip-address@<=10.1.0: '>=10.1.1'
  nitropack@<2.13.4: '>=2.13.4'
  srvx@<0.11.13: '>=0.11.13'
