name: Deploy to Production

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'v1.0.0'
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Install WireGuard
        run: sudo apt-get update && sudo apt-get install -y wireguard resolvconf

      - name: Connect to Corporate VPN
        run: |
          # Write the secret config to the correct WireGuard directory
          echo "${{ secrets.WIREGUARD_CONFIG }}" | sudo tee /etc/wireguard/wg0.conf > /dev/null
          
          # Ensure strict permissions so wg-quick doesn't complain
          sudo chmod 600 /etc/wireguard/wg0.conf
          
          # Bring the tunnel up
          sudo wg-quick up wg0
          
          # Optional: Ping the server once to verify the tunnel is routing properly
          ping -c 1 ${{ secrets.HOST }}
      - name: Deploy to PROD server via SSH
        uses: appleboy/ssh-action@v1
        env:
          DATABASE_URL: ${{ vars.DATABASE_URL }}
          SHADOW_DATABASE_URL: ${{ vars.SHADOW_DATABASE_URL }}
          SESSION_SECRET: ${{ vars.SESSION_SECRET }}
          INITIAL_USER_PASSWORD: ${{ vars.INITIAL_USER_PASSWORD }}
          PORT: ${{ vars.PORT }}
          COOKIE_SECURE: true
          NOTIFICATION_API_URL: ${{ vars.NOTIFICATION_API_URL }}
          NOTIFICATION_TOKEN_API_URL: ${{ vars.NOTIFICATION_TOKEN_API_URL }}
          NOTIFICATION_TOKEN_NAME: ${{ vars.NOTIFICATION_TOKEN_NAME }}
          NOTIFICATION_TOKEN_EMAIL: ${{ vars.NOTIFICATION_TOKEN_EMAIL }}
          NOTIFICATION_TOKEN_APPSNAME: ${{ vars.NOTIFICATION_TOKEN_APPSNAME }}
          APP_URL: ${{ vars.APP_URL }}
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: DATABASE_URL, SHADOW_DATABASE_URL, SESSION_SECRET, INITIAL_USER_PASSWORD, PORT, COOKIE_SECURE
          script: |
            set -e 
            mkdir -p /home/${{ secrets.USERNAME }}/app/mars
            cd /home/${{ secrets.USERNAME }}/app/mars
            # State-Aware Git Sync
            if [ ! -d ".git" ]; then
              echo "Repository not found. Cloning fresh..."
              # Replace this URL with your actual repository URL
              git clone git@github.com:GAM-Retail/mars.git .
            else
              echo "Repository exists. Fetching updates..."
              git fetch origin master
              git reset --hard origin/master
            fi
            
            echo "Injecting production secrets into .env file..."
            cat <<EOF > .env
            DATABASE_URL=$DATABASE_URL
            SHADOW_DATABASE_URL=$SHADOW_DATABASE_URL
            SESSION_SECRET=$SESSION_SECRET
            INITIAL_USER_PASSWORD=$INITIAL_USER_PASSWORD
            PORT=$PORT
            COOKIE_SECURE=COOKIE_SECURE
            NOTIFICATION_API_URL: $NOTIFICATION_API_URL
            NOTIFICATION_TOKEN_API_URL: $NOTIFICATION_TOKEN_API_URL
            NOTIFICATION_TOKEN_NAME: $NOTIFICATION_TOKEN_NAME
            NOTIFICATION_TOKEN_EMAIL: $NOTIFICATION_TOKEN_EMAIL
            NOTIFICATION_TOKEN_APPSNAME: $NOTIFICATION_TOKEN_APPSNAME
            APP_URL: $APP_URL
            EOF
            
            docker compose --env-file .env build --no-cache
            docker compose --env-file .env up -d --force-recreate
            docker image prune -f
            echo "Deployed latest master to PROD server successfully"
      - name: Disconnect VPN
        if: always()
        run: sudo wg-quick down wg0
