name: Deploy to Development

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Deploy to DEV server via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e 

            cd /opt/mars

            git fetch origin master
            git reset --hard origin/master

            docker compose --env-file .env build 

            docker compose --env-file .env up -d

            docker image prune -f

            echo "Deployed latest master to DEV server successfully"
